### ISSUE TITLE
why not using abstract information for neighbour nodes in Rich textual context? 

### ISSUE THREAD

**Issue by initzhang** [TRAIS-Lab/LLM-Structured-Data#2]
Hi team, thanks for this interesting work!

However, I am a little confused about the setting for `Rich textual context`. And I would be grateful if you could provide some explanations.

Specifically, you defined the `Rich textual context ` as follows:
```
For the target node, title and abstract are given for cora, pubmed, ogbn-arxiv and arxiv-2023, product title and product content are given for ogbn-product. For other neighbors, we use their titles only.
```

I am wondering what motivates you to exclude the `abstract/product content` from neighbours nodes but only use their titles?

**Comment by Jn-Huang** [comment]
Hello! Thanks for your question. We exclude the neighbors' abstract or product content for two main reasons:

1. Our initial tests showed no notable improvement in performance when incorporating the neighbors' abstracts or product information. Typically, the titles alone are adequate for providing the necessary context.
2. To manage token limitations and costs effectively, we opt to exclude the lengthy abstracts and product details from our prompts.

If you have further question, feel free to ask!

**Comment by initzhang** [comment]
Hi @Jn-Huang thanks for your reply!
